server:
  port: 8081
spring:
  application:
    name: fraud-service
  datasource:
    username: 'root'
    password: 'password'
    url: jdbc:mysql://localhost:3306/cigma_2023_tp2_springcloud_fraud_db?serverTimezone=UTC
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true